name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # Cambia 'main' por tu rama principal si es necesario

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install -g firebase-tools
          npm ci

      - name: Deploy to Firebase
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
