name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Esto se ejecuta cuando haces push a la rama "main" (puedes usar otra si es el caso)

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza la última versión de Ubuntu para ejecutar los trabajos

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Este paso descarga el código de tu repositorio

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Configura Node.js en el flujo de trabajo
      with:
        node-version: '16'  # Asegúrate de usar la versión correcta de Node.js según tu proyecto

    - name: Install dependencies
      run: npm install  # Instala las dependencias de tu proyecto (asegúrate de tener un archivo package.json)

    - name: Build the project
      run: npm run build  # Este paso ejecuta el comando para construir tu aplicación. Cambia este paso si usas otro comando para construir el proyecto.

    - name: Firebase deploy
      uses: wzieba/Firebase-Action@v2  # Acción para hacer el despliegue en Firebase Hosting
      with:
        firebase_token: ${{secrets.FIREBASE_TOKEN}}  # Necesitas agregar el token de Firebase en los secretos
